import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // name matches the font
});

export const metadata: Metadata = {
  title: "Osiris",
  description: "Generated by Osiris",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased `}>
        <NextAuthProvider>
          <div>
            <Navbar />
            <main className="min-h-[calc(100vh-166px)]">{children}</main>
            <Footer />
          </div>
        </NextAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
